server:
  port: 8082
  
spring:  datasource:    url: jdbc:mysql://localhost:3306/CollageDataBase
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:    hibernate:      ddl-auto: update
    show-sql: true    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  application:    name: COLLAGE-SERVICE
    
    #End point url: http://localhost:8082/collage/collageId/1
    #http://localhost:8082/collage/add
    